#eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka1:8761/eureka,http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka2:8762/eureka,http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka3:8763/eureka
  instance:
    prefer-ip-address: false

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#ribbon
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 2000

spring:
    #rabbitmq
    rabbitmq:
      host: rabbitmq
      username: chris
      password: 123123
      virtual-host: prontera
      listener:
        retry:
          enabled: true
      template:
        retry:
          enabled: true
        mandatory: true
      publisher-returns: true
      publisher-confirms: true
    #sleuth
    sleuth:
      sampler:
        percentage: 1
      integration:
        enabled: false
      scheduled:
        skip-pattern: "^org.*HystrixStreamTask$"