eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka1:8763/eureka/,http://user:${REGISTRY_SERVER_PASSWORD:password}@eureka2:8762/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 2000
spring:
  rabbitmq:
    host: rabbitmq
    username: chris
    password: 123123
    virtual-host: prontera
    listener:
      retry:
        enabled: true
    template:
      retry:
        enabled: true
      mandatory: true
    publisher-confirms: true
    publisher-returns: true
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
authserver:
    hostname: auth-service
    port: 10736
    contextPath: /uaa
security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current